#! /bin/bash

DEPLOY_FOLDER=deployment
GIT_URL="git@github.com:cdinescu"

# Project build function

buildProject() {
  project_folder=$1
  echo -e "\n Building: $project_fold.........................................\n"
  cd ${project_folder}
  # Generate the build folder, which later are used by the projects' Dockerfile when creating the image
  gradle bootJar
  # Go back
  cd ..
}

rm -rf $DEPLOY_FOLDER
mkdir $DEPLOY_FOLDER 
cd $DEPLOY_FOLDER

# Clone the application's microservices
git clone ${GIT_URL}/eureka-service.git
git clone ${GIT_URL}/config-server.git
git clone ${GIT_URL}/food-service.git
git clone ${GIT_URL}/users-service.git
git clone ${GIT_URL}/gateway-service.git
git clone ${GIT_URL}/diary-service.git
git clone ${GIT_URL}/ask-oracle-service.git
git clone ${GIT_URL}/central-config.git
git clone ${GIT_URL}/nutrient-ranks.git

echo -e "\n\n"

# Folder name array for the projects which need to be built (those with source code)
declare -a services_to_build=(eureka-service config-server food-service gateway-service diary-service ask-oracle-service)

for project in "${services_to_build[@]}"
do
   echo "Building project: $project"
   buildProject $project
done

# Go back, to the folder containing the docker-compose.yaml
cd ..

