apiVersion: apps/v1
kind: Deployment
metadata:
  name: eureka-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eureka
  template:
    metadata:
      name: eureka1
      labels:
        app: eureka
        type: backend
    spec:
      containers:
        - name: eureka-container
          image: villanelle/vitanum-naming-server
---
apiVersion: v1
kind: Service
metadata:
  name: naming-server
spec:
  ports:
    - targetPort: 8761
      port: 8761
  selector:
    app: eureka

