apiVersion: apps/v1
kind: Deployment
metadata:
  name: eureka-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eureka
  template:
    metadata:
      name: naming-server
      labels:
        app: eureka
        type: backend
    spec:
      containers:
        - name: eureka-container
          image: villanelle/vitanum-naming-server