apiVersion: apps/v1
kind: Deployment
metadata:
  name: food-service-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: food-service
  template:
    metadata:
      name: food-service
      labels:
        app: food-service
        type: backend
    spec:
      containers:
        - name: food-service-container
          image: villanelle/vitanum-food-service
---
apiVersion: v1
kind: Service
metadata:
  name: food-service
spec:
  ports:
    - targetPort: 8022
      port: 8022
  selector:
    app: food-service

