apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      name: gateway-service
      labels:
        app: gateway
        type: backend
    spec:
      containers:
        - name: gateway-container
          image: villanelle/vitanum-gateway-service